"""Read local dataset files, invoking the download script only for missing data."""

from __future__ import annotations

import json
import os
from pathlib import Path
import shlex
import subprocess
import sys


def missing_dataset(name: str, root: Path) -> FileNotFoundError:
    command = shlex.join(
        ["python", "scripts/download_datasets.py", "--datasets", name,
         "--data-root", str(root.resolve())]
    )
    return FileNotFoundError(
        f"No complete local dataset found for {name} under {root}. "
        f"Prepare it first with: {command}"
    )


def load_local_huggingface(name: str, root: Path, config: dict):
    """Find the dataset by its source metadata, then memory-map its Arrow shards.

    Cache directory hashes are generated by datasets and must not be hardcoded.
    In particular, both CIFAR datasets use the same 'parquet' builder name.
    """
    from datasets import Dataset, DatasetDict, concatenate_datasets

    candidates = []
    for info_path in (root / "huggingface").glob("**/dataset_info.json"):
        try:
            info = json.loads(info_path.read_text(encoding="utf-8"))
        except (OSError, ValueError):
            continue
        sources = info.get("download_checksums", {})
        source = config["source"]
        prefixes = (
            f"hf://datasets/{source}@",
            f"https://huggingface.co/datasets/{source}/",
        )
        if not sources or not all(
            url.startswith(prefixes) for url in sources
        ):
            continue
        if "subset" in config and info.get("config_name") != config["subset"]:
            continue
        required_splits = {"train", "validation" if name == "qnli" else "test"}
        if not required_splits.issubset(info.get("splits", {})):
            continue
        candidates.append((info_path, info))

    # Match the library's preference for the latest prepared, complete cache.
    candidates.sort(
        key=lambda item: (item[0].stat().st_mtime_ns, str(item[0])), reverse=True
    )
    for info_path, info in candidates:
        splits = {}
        for split, metadata in info["splits"].items():
            prefix = f"{info['dataset_name']}-{split}"
            single = info_path.parent / f"{prefix}.arrow"
            files = [single] if single.is_file() else sorted(
                info_path.parent.glob(f"{prefix}-?????-of-?????.arrow")
            )
            expected_shards = len(
                metadata.get("shard_lengths") or [metadata["num_examples"]]
            )
            if len(files) != expected_shards:
                break
            shards = [Dataset.from_file(str(path), split=split) for path in files]
            if sum(len(shard) for shard in shards) != metadata["num_examples"]:
                break
            splits[split] = shards[0] if len(shards) == 1 else concatenate_datasets(shards)
        else:
            return DatasetDict(splits)
    raise missing_dataset(name, root)


def local_openml_path(root: Path, config: dict) -> Path:
    _, name, version = config["source"].split(":", maxsplit=2)
    return root / "openml" / f"{name}-v{version}.joblib"


def load_local_openml(name: str, root: Path, config: dict):
    import joblib

    path = local_openml_path(root, config)
    if not path.is_file():
        raise missing_dataset(name, root)
    return joblib.load(path)


def prepare_dataset(name: str, root: Path) -> None:
    """Allow downloads in a separate process while evaluation stays offline."""
    script = Path(__file__).resolve().parents[2] / "scripts" / "download_datasets.py"
    # Evaluation sets these before importing HF. The preparation process needs
    # network access when a required dataset, tokenizer, or weight file is absent.
    env = os.environ.copy()
    for variable in ("HF_HUB_OFFLINE", "HF_DATASETS_OFFLINE", "TRANSFORMERS_OFFLINE"):
        env.pop(variable, None)
    subprocess.run(
        [sys.executable, str(script), "--datasets", name,
         "--data-root", str(root.resolve())],
        env=env,
        check=True,
    )


def load_dataset_or_download(name: str, root: Path, config: dict):
    loader = (
        load_local_openml if config["source"].startswith("openml:")
        else load_local_huggingface
    )
    try:
        return loader(name, root, config)
    except FileNotFoundError:
        prepare_dataset(name, root)
    return loader(name, root, config)


def model_is_cached(model_name: str, cache_dir: Path) -> bool:
    """Check configuration and all weight shards without constructing a model."""
    from huggingface_hub import try_to_load_from_cache

    def local_file(filename):
        if Path(model_name).is_dir():
            path = Path(model_name) / filename
        else:
            path = try_to_load_from_cache(model_name, filename, cache_dir=str(cache_dir))
        return Path(path) if isinstance(path, (str, Path)) and Path(path).is_file() else None

    if local_file("config.json") is None:
        return False
    # Follow Transformers' preference for safetensors before PyTorch weights.
    for filename in ("model.safetensors", "model.safetensors.index.json",
                     "pytorch_model.bin", "pytorch_model.bin.index.json"):
        path = local_file(filename)
        if path is None:
            continue
        if not filename.endswith(".index.json"):
            return True
        shards = json.loads(path.read_text(encoding="utf-8")).get("weight_map", {})
        return bool(shards) and all(
            local_file(shard) is not None for shard in set(shards.values())
        )
    return False


def ensure_model_cached(name: str, root: Path, model_name: str) -> None:
    if not model_is_cached(model_name, root / "huggingface"):
        prepare_dataset(name, root)
        if not model_is_cached(model_name, root / "huggingface"):
            raise FileNotFoundError(
                f"Model files for {model_name} are still missing after preparation"
            )
